name: PULL request

on:
 pull_request:
  types: opened

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - name: Log into Github Container registry
     uses: docker/login-action@v1
     with:
      registry: ghcr.io
      username: ${{github.actor}}
      pssword:  ${{github.GITHUB_TOKEN}}
   - name: Set Docker image tag
     id: meta
     run: echo "tag=ghcr.io/${{ github.repository }}/pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
   - name: Build Docker image
     run: |
          docker build -t ${{ steps.meta.outputs.tag }} .
   - name: Push Docker image
     run: |
          docker push ${{ steps.meta.outputs.tag }}
   - name: Comment image link on PR
     uses: peter-evans/create-or-update-comment@v4
     with:
       token: ${{ secrets.GITHUB_TOKEN }}
       issue-number: ${{ github.event.pull_request.number }}
       body: |
            🚀 Docker image built for this PR:  
            `${{ steps.meta.outputs.tag }}`
