name: Environment with Inputs

on:
 workflow_dispatch:
  inputs:
   TARGET_ENVIRONMENT:
    type: environment
    default: dev

jobs:
 build:
  runs-on: ubuntu-latest
  environment: ${{inputs.TARGET_ENVIRONMENT}}
  steps:
   - name: Display secret
     run: echo 'Secret value is ${{secrets.TAR_SECRET}}'
