name: First WorkFlow CI

on: 
 push:
  branches:
   - 'feature'
   - 'master'

jobs:
 build_java:
   runs-on: self-hosted
   steps:
     - name: Setup Java JDK
       uses: actions/setup-java@v4.6.0
       with:
        java-version: '17'
        distribution: 'microsoft'
 test:
   needs: build_java
   runs-on: self-hosted
   steps:
     - run: echo 'test' 
   
 

 
