name: Build and push

env:
 DOCKER_IMAGE: workflow
on:
 push:
  branches:
   - master

jobs:
 build:
  env:
   DOCKER_IMAGE: job
  runs-on: ubuntu-latest
  steps:  
   -  name: Display
    
      run: echo '${{env.DOCKER_IMAGE}}'
