name: Build and push

env:
 DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
on:
 push:
  branches:
   - master

jobs:
 build:
 
  runs-on: ubuntu-latest
  steps:  
   -  name: Display
    
      run: echo '${{env.DOCKER_USERNAME}}'
